{
	"0_HTMLDivElement": [
		// null, 
		// "align", 
		// "constructor"
	],

	"1_HTMLElement": [
		// null, 
		"accessKey", 
		"blur", 
		"click", 
		// "constructor", 
		"contentEditable", 
		"dataset", 
		// "dir", 
		// "draggable", 
		"focus", 
		"hidden", 
		"innerText", 
		"isContentEditable", 
		"lang", 
		"offsetHeight", 
		"offsetLeft", 
		"offsetParent", 
		"offsetTop", 
		"offsetWidth", 
		"outerText", 
		// "spellcheck", 
		"style", 
		// "tabIndex", 
		"title", 
		// "translate",

		// 事件
		// "onabort", 
		// "onauxclick", 
		// "onblur", 
		// "oncancel", 
		// "oncanplay", 
		// "oncanplaythrough", 
		// "onchange", 
		// "onclick", 
		// "onclose", 
		// "oncontextmenu", 
		// "oncuechange", 
		// "ondblclick", 
		// "ondrag", 
		// "ondragend", 
		// "ondragenter", 
		// "ondragleave", 
		// "ondragover", 
		// "ondragstart", 
		// "ondrop", 
		// "ondurationchange", 
		// "onemptied", 
		// "onended", 
		// "onerror", 
		// "onfocus", 
		// "ongotpointercapture", 
		// "oninput", 
		// "oninvalid", 
		// "onkeydown", 
		// "onkeypress", 
		// "onkeyup", 
		// "onload", 
		// "onloadeddata", 
		// "onloadedmetadata", 
		// "onloadstart", 
		// "onlostpointercapture", 
		// "onmousedown", 
		// "onmouseenter", 
		// "onmouseleave", 
		// "onmousemove", 
		// "onmouseout", 
		// "onmouseover", 
		// "onmouseup", 
		// "onmousewheel", 
		// "onpause", 
		// "onplay", 
		// "onplaying", 
		// "onpointercancel", 
		// "onpointerdown", 
		// "onpointerenter", 
		// "onpointerleave", 
		// "onpointermove", 
		// "onpointerout", 
		// "onpointerover", 
		// "onpointerup", 
		// "onprogress", 
		// "onratechange", 
		// "onreset", 
		// "onresize", 
		// "onscroll", 
		// "onseeked", 
		// "onseeking", 
		// "onselect", 
		// "onshow", 
		// "onstalled", 
		// "onsubmit", 
		// "onsuspend", 
		// "ontimeupdate", 
		// "ontoggle", 
		// "onvolumechange", 
		// "onwaiting", 
	],

	"2_Element": [
		// null, 
		// null, 
		"after", 
		// "animate", 
		"append", 
		"assignedSlot", 
		"attachShadow", 
		"attributes", 
		"before", 
		"childElementCount", 
		"children", 
		"classList", 
		"className", 
		"clientHeight", 
		"clientLeft", 
		"clientTop", 
		"clientWidth", 
		"closest", 
		"constructor", 
		"createShadowRoot", 
		"firstElementChild", 
		"getAttribute", 
		"getAttributeNS", 
		"getAttributeNode", 
		"getAttributeNodeNS", 
		"getBoundingClientRect", 
		"getClientRects", 
		"getDestinationInsertionPoints", 
		"getElementsByClassName", 
		"getElementsByTagName", 
		"getElementsByTagNameNS", 
		"hasAttribute", 
		"hasAttributeNS", 
		"hasAttributes", 
		"hasPointerCapture", 
		"id", 
		"innerHTML", 
		! "insertAdjacentElement", 
		!"insertAdjacentHTML", 
		!"insertAdjacentText", 
		"lastElementChild", 
		"localName", 
		"matches", 
		"namespaceURI", 
		"nextElementSibling", 
		// "onbeforecopy", 
		// "onbeforecut", 
		// "onbeforepaste", 
		// "oncopy", 
		// "oncut", 
		// "onpaste", 
		// "onsearch", 
		// "onselectstart", 
		// "onwebkitfullscreenchange", 
		// "onwebkitfullscreenerror", 
		// "onwheel", 
		"outerHTML", 
		"prefix", 
		"prepend", 
		"previousElementSibling", 
		"querySelector", 
		"querySelectorAll", 
		"releasePointerCapture", 
		"remove", 
		"removeAttribute", 
		"removeAttributeNS", 
		"removeAttributeNode", 
		"replaceWith", 
		"requestPointerLock", 
		"scrollHeight", 
		"scrollIntoView", 
		"scrollIntoViewIfNeeded", 
		"scrollLeft", 
		"scrollTop", 
		"scrollWidth", 
		"setAttribute", 
		"setAttributeNS", 
		"setAttributeNode", 
		"setAttributeNodeNS", 
		"setPointerCapture", 
		"shadowRoot", 
		"slot", 
		"tagName", 
		"webkitMatchesSelector", 
		"webkitRequestFullScreen", 
		"webkitRequestFullscreen"
	],

	"3_Node": [
		// null, 
		// "ATTRIBUTE_NODE", 
		// "CDATA_SECTION_NODE", 
		// "COMMENT_NODE", 
		// "DOCUMENT_FRAGMENT_NODE", 
		// "DOCUMENT_NODE", 
		// "DOCUMENT_POSITION_CONTAINED_BY", 
		// "DOCUMENT_POSITION_CONTAINS", 
		// "DOCUMENT_POSITION_DISCONNECTED", 
		// "DOCUMENT_POSITION_FOLLOWING", 
		// "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC", 
		// "DOCUMENT_POSITION_PRECEDING", 
		// "DOCUMENT_TYPE_NODE", 
		// "ELEMENT_NODE", 
		// "ENTITY_NODE", 
		// "ENTITY_REFERENCE_NODE", 
		// "NOTATION_NODE", 
		// "PROCESSING_INSTRUCTION_NODE", 
		// "TEXT_NODE", 
		"appendChild", 
		"baseURI", 
		"childNodes", 
		"cloneNode", 
		"compareDocumentPosition", 
		"constructor", 
		"contains", 
		"firstChild", 
		"getRootNode", 
		"hasChildNodes", 
		"insertBefore", 
		"isConnected", 
		"isDefaultNamespace", 
		"isEqualNode", 
		"isSameNode", 
		"lastChild", 
		"lookupNamespaceURI", 
		"lookupPrefix", 
		"nextSibling", 
		"nodeName", 
		"nodeType", 
		"nodeValue", 
		? "normalize", 
		"ownerDocument", 
		"parentElement", 
		"parentNode", 
		"previousSibling", 
		"removeChild", 
		"replaceChild", 
		"textContent"
	],

	"4_EventTarget": [
		null, 
		"addEventListener", 
		"constructor", 
		"dispatchEvent", 
		"removeEventListener"
	],

	"5_object": [
		// "__defineGetter__", 
		// "__defineSetter__", 
		// "__lookupGetter__", 
		// "__lookupSetter__", 
		// "__proto__", 
		"constructor", 
		"hasOwnProperty", 
		"isPrototypeOf", 
		"propertyIsEnumerable", 
		"toLocaleString", 
		"toString", 
		"valueOf"
	]
}

{
	"0_HTMLInputElement": [
		null, 
		"accept", 
		"align", 
		"alt", 
		"autocapitalize", 
		"autocomplete", 
		"autofocus", 
		"checkValidity", 
		"checked", 
		"constructor", 
		"defaultChecked", 
		"defaultValue", 
		"dirName", 
		"disabled", 
		"files", 
		"form", 
		"formAction", 
		"formEnctype", 
		"formMethod", 
		"formNoValidate", 
		"formTarget", 
		"height", 
		"incremental", 
		"indeterminate", 
		"labels", 
		"list", 
		"max", 
		"maxLength", 
		"min", 
		"minLength", 
		"multiple", 
		"name", 
		"pattern", 
		"placeholder", 
		"readOnly", 
		"reportValidity", 
		"required", 
		"select", 
		"selectionDirection", 
		"selectionEnd", 
		"selectionStart", 
		"setCustomValidity", 
		"setRangeText", 
		"setSelectionRange", 
		"size", 
		"src", 
		"step", 
		"stepDown", 
		"stepUp", 
		"type", 
		"useMap", 
		"validationMessage", 
		"validity", 
		"value", 
		"valueAsDate", 
		"valueAsNumber", 
		"webkitEntries", 
		"webkitdirectory", 
		"width", 
		"willValidate"
	],

	"1_HTMLElement": [
		null, 
		"accessKey", 
		"blur", 
		"click", 
		"constructor", 
		"contentEditable", 
		"dataset", 
		"dir", 
		"draggable", 
		"focus", 
		"hidden", 
		"innerText", 
		"isContentEditable", 
		"lang", 
		"offsetHeight", 
		"offsetLeft", 
		"offsetParent", 
		"offsetTop", 
		"offsetWidth", 
		"onabort", 
		"onauxclick", 
		"onblur", 
		"oncancel", 
		"oncanplay", 
		"oncanplaythrough", 
		"onchange", 
		"onclick", 
		"onclose", 
		"oncontextmenu", 
		"oncuechange", 
		"ondblclick", 
		"ondrag", 
		"ondragend", 
		"ondragenter", 
		"ondragleave", 
		"ondragover", 
		"ondragstart", 
		"ondrop", 
		"ondurationchange", 
		"onemptied", 
		"onended", 
		"onerror", 
		"onfocus", 
		"ongotpointercapture", 
		"oninput", 
		"oninvalid", 
		"onkeydown", 
		"onkeypress", 
		"onkeyup", 
		"onload", 
		"onloadeddata", 
		"onloadedmetadata", 
		"onloadstart", 
		"onlostpointercapture", 
		"onmousedown", 
		"onmouseenter", 
		"onmouseleave", 
		"onmousemove", 
		"onmouseout", 
		"onmouseover", 
		"onmouseup", 
		"onmousewheel", 
		"onpause", 
		"onplay", 
		"onplaying", 
		"onpointercancel", 
		"onpointerdown", 
		"onpointerenter", 
		"onpointerleave", 
		"onpointermove", 
		"onpointerout", 
		"onpointerover", 
		"onpointerup", 
		"onprogress", 
		"onratechange", 
		"onreset", 
		"onresize", 
		"onscroll", 
		"onseeked", 
		"onseeking", 
		"onselect", 
		"onshow", 
		"onstalled", 
		"onsubmit", 
		"onsuspend", 
		"ontimeupdate", 
		"ontoggle", 
		"onvolumechange", 
		"onwaiting", 
		"outerText", 
		"spellcheck", 
		"style", 
		"tabIndex", 
		"title", 
		"translate"
	],

	"2_Element": [
		null, 
		null, 
		"after", 
		"animate", 
		"append", 
		"assignedSlot", 
		"attachShadow", 
		"attributes", 
		"before", 
		"childElementCount", 
		"children", 
		"classList", 
		"className", 
		"clientHeight", 
		"clientLeft", 
		"clientTop", 
		"clientWidth", 
		"closest", 
		"constructor", 
		"createShadowRoot", 
		"firstElementChild", 
		"getAttribute", 
		"getAttributeNS", 
		"getAttributeNode", 
		"getAttributeNodeNS", 
		"getBoundingClientRect", 
		"getClientRects", 
		"getDestinationInsertionPoints", 
		"getElementsByClassName", 
		"getElementsByTagName", 
		"getElementsByTagNameNS", 
		"hasAttribute", 
		"hasAttributeNS", 
		"hasAttributes", 
		"hasPointerCapture", 
		"id", 
		"innerHTML", 
		"insertAdjacentElement", 
		"insertAdjacentHTML", 
		"insertAdjacentText", 
		"lastElementChild", 
		"localName", 
		"matches", 
		"namespaceURI", 
		"nextElementSibling", 
		"onbeforecopy", 
		"onbeforecut", 
		"onbeforepaste", 
		"oncopy", 
		"oncut", 
		"onpaste", 
		"onsearch", 
		"onselectstart", 
		"onwebkitfullscreenchange", 
		"onwebkitfullscreenerror", 
		"onwheel", 
		"outerHTML", 
		"prefix", 
		"prepend", 
		"previousElementSibling", 
		"querySelector", 
		"querySelectorAll", 
		"releasePointerCapture", 
		"remove", 
		"removeAttribute", 
		"removeAttributeNS", 
		"removeAttributeNode", 
		"replaceWith", 
		"requestPointerLock", 
		"scrollHeight", 
		"scrollIntoView", 
		"scrollIntoViewIfNeeded", 
		"scrollLeft", 
		"scrollTop", 
		"scrollWidth", 
		"setAttribute", 
		"setAttributeNS", 
		"setAttributeNode", 
		"setAttributeNodeNS", 
		"setPointerCapture", 
		"shadowRoot", 
		"slot", 
		"tagName", 
		"webkitMatchesSelector", 
		"webkitRequestFullScreen", 
		"webkitRequestFullscreen"
	],

	"3_Node": [
		null, 
		"ATTRIBUTE_NODE", 
		"CDATA_SECTION_NODE", 
		"COMMENT_NODE", 
		"DOCUMENT_FRAGMENT_NODE", 
		"DOCUMENT_NODE", 
		"DOCUMENT_POSITION_CONTAINED_BY", 
		"DOCUMENT_POSITION_CONTAINS", 
		"DOCUMENT_POSITION_DISCONNECTED", 
		"DOCUMENT_POSITION_FOLLOWING", 
		"DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC", 
		"DOCUMENT_POSITION_PRECEDING", 
		"DOCUMENT_TYPE_NODE", 
		"ELEMENT_NODE", 
		"ENTITY_NODE", 
		"ENTITY_REFERENCE_NODE", 
		"NOTATION_NODE", 
		"PROCESSING_INSTRUCTION_NODE", 
		"TEXT_NODE", 
		"appendChild", 
		"baseURI", 
		"childNodes", 
		"cloneNode", 
		"compareDocumentPosition", 
		"constructor", 
		"contains", 
		"firstChild", 
		"getRootNode", 
		"hasChildNodes", 
		"insertBefore", 
		"isConnected", 
		"isDefaultNamespace", 
		"isEqualNode", 
		"isSameNode", 
		"lastChild", 
		"lookupNamespaceURI", 
		"lookupPrefix", 
		"nextSibling", 
		"nodeName", 
		"nodeType", 
		"nodeValue", 
		"normalize", 
		"ownerDocument", 
		"parentElement", 
		"parentNode", 
		"previousSibling", 
		"removeChild", 
		"replaceChild", 
		"textContent"
	],

	"4_EventTarget": [
		null, 
		"addEventListener", 
		"constructor", 
		"dispatchEvent", 
		"removeEventListener"
	],

	"5_object": [
		"__defineGetter__", 
		"__defineSetter__", 
		"__lookupGetter__", 
		"__lookupSetter__", 
		"__proto__", 
		"constructor", 
		"hasOwnProperty", 
		"isPrototypeOf", 
		"propertyIsEnumerable", 
		"toLocaleString", 
		"toString", 
		"valueOf"
	]
}

{
	"0_HTMLDocument":[
		// null,
		"alinkColor",
		"all",
		"bgColor",
		"captureEvents",
		"clear",
		"constructor",
		"fgColor",
		"linkColor",
		"releaseEvents",
		"vlinkColor"
	],
	"1_Document":[
		// null,
		// null,
		"URL",
		"activeElement",
		"adoptNode",
		"anchors",
		"append",
		"applets",
		"body",
		"caretRangeFromPoint",
		"characterSet",
		"charset",
		"childElementCount",
		"children",
		"close",
		"compatMode",
		"constructor",
		"contentType",
		"cookie",
		"createAttribute",
		"createAttributeNS",
		"createCDATASection",
		"createComment",
		"createDocumentFragment",
		"createElement",
		"createElementNS",
		"createEvent",
		"createExpression",
		"createNSResolver",
		"createNodeIterator",
		"createProcessingInstruction",
		"createRange",
		"createTextNode",
		"createTreeWalker",
		"currentScript",
		"defaultView",
		"designMode",
		"dir",
		"doctype",
		"documentElement",
		"documentURI",
		"domain",
		"elementFromPoint",
		"elementsFromPoint",
		"embeds",
		"evaluate",
		"execCommand",
		"exitPointerLock",
		"firstElementChild",
		"fonts",
		"forms",
		"getElementById",
		"getElementsByClassName",
		"getElementsByName",
		"getElementsByTagName",
		"getElementsByTagNameNS",
		"getSelection",
		"hasFocus",
		"head",
		"hidden",
		"images",
		"implementation",
		"importNode",
		"inputEncoding",
		"lastElementChild",
		"lastModified",
		"links",
		"onabort",
		"onauxclick",
		"onbeforecopy",
		"onbeforecut",
		"onbeforepaste",
		"onblur",
		"oncancel",
		"oncanplay",
		"oncanplaythrough",
		"onchange",
		"onclick",
		"onclose",
		"oncontextmenu",
		"oncopy",
		"oncuechange",
		"oncut",
		"ondblclick",
		"ondrag",
		"ondragend",
		"ondragenter",
		"ondragleave",
		"ondragover",
		"ondragstart",
		"ondrop",
		"ondurationchange",
		"onemptied",
		"onended",
		"onerror",
		"onfocus",
		"ongotpointercapture",
		"oninput",
		"oninvalid",
		"onkeydown",
		"onkeypress",
		"onkeyup",
		"onload",
		"onloadeddata",
		"onloadedmetadata",
		"onloadstart",
		"onlostpointercapture",
		"onmousedown",
		"onmouseenter",
		"onmouseleave",
		"onmousemove",
		"onmouseout",
		"onmouseover",
		"onmouseup",
		"onmousewheel",
		"onpaste",
		"onpause",
		"onplay",
		"onplaying",
		"onpointercancel",
		"onpointerdown",
		"onpointerenter",
		"onpointerleave",
		"onpointerlockchange",
		"onpointerlockerror",
		"onpointermove",
		"onpointerout",
		"onpointerover",
		"onpointerup",
		"onprogress",
		"onratechange",
		"onreadystatechange",
		"onreset",
		"onresize",
		"onscroll",
		"onsearch",
		"onseeked",
		"onseeking",
		"onselect",
		"onselectionchange",
		"onselectstart",
		"onshow",
		"onstalled",
		"onsubmit",
		"onsuspend",
		"ontimeupdate",
		"ontoggle",
		"onvolumechange",
		"onwaiting",
		"onwebkitfullscreenchange",
		"onwebkitfullscreenerror",
		"onwheel",
		"open",
		"origin",
		"plugins",
		"pointerLockElement",
		"preferredStylesheetSet",
		"prepend",
		"queryCommandEnabled",
		"queryCommandIndeterm",
		"queryCommandState",
		"queryCommandSupported",
		"queryCommandValue",
		"querySelector",
		"querySelectorAll",
		"readyState",
		"referrer",
		"registerElement",
		"rootElement",
		"scripts",
		"scrollingElement",
		"selectedStylesheetSet",
		"styleSheets",
		"title",
		"visibilityState",
		"webkitCancelFullScreen",
		"webkitCurrentFullScreenElement",
		"webkitExitFullscreen",
		"webkitFullscreenElement",
		"webkitFullscreenEnabled",
		"webkitHidden",
		"webkitIsFullScreen",
		"webkitVisibilityState",
		"write",
		"writeln",
		"xmlEncoding",
		"xmlStandalone",
		"xmlVersion"
	],
	"2_Node":[
		null,
		"ATTRIBUTE_NODE",
		"CDATA_SECTION_NODE",
		"COMMENT_NODE",
		"DOCUMENT_FRAGMENT_NODE",
		"DOCUMENT_NODE",
		"DOCUMENT_POSITION_CONTAINED_BY",
		"DOCUMENT_POSITION_CONTAINS",
		"DOCUMENT_POSITION_DISCONNECTED",
		"DOCUMENT_POSITION_FOLLOWING",
		"DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
		"DOCUMENT_POSITION_PRECEDING",
		"DOCUMENT_TYPE_NODE",
		"ELEMENT_NODE",
		"ENTITY_NODE",
		"ENTITY_REFERENCE_NODE",
		"NOTATION_NODE",
		"PROCESSING_INSTRUCTION_NODE",
		"TEXT_NODE",
		"appendChild",
		"baseURI",
		"childNodes",
		"cloneNode",
		"compareDocumentPosition",
		"constructor",
		"contains",
		"firstChild",
		"getRootNode",
		"hasChildNodes",
		"insertBefore",
		"isConnected",
		"isDefaultNamespace",
		"isEqualNode",
		"isSameNode",
		"lastChild",
		"lookupNamespaceURI",
		"lookupPrefix",
		"nextSibling",
		"nodeName",
		"nodeType",
		"nodeValue",
		"normalize",
		"ownerDocument",
		"parentElement",
		"parentNode",
		"previousSibling",
		"removeChild",
		"replaceChild",
		"textContent"
	],
	"3_EventTarget":[
		null,
		"addEventListener",
		"constructor",
		"dispatchEvent",
		"removeEventListener"
	],
	"4_object":[
		"__defineGetter__",
		"__defineSetter__",
		"__lookupGetter__",
		"__lookupSetter__",
		"__proto__",
		"constructor",
		"hasOwnProperty",
		"isPrototypeOf",
		"propertyIsEnumerable",
		"toLocaleString",
		"toString",
		"valueOf"
	]
}

